name: 'MADLOG deploy action'
description: 'Description of your action'
inputs:
  aws-key:
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        echo ${REPO}
        echo ${{axs-key}}
        env

      shell: bash
