name: 'MADLOG deploy action'
description: 'Description of your action'
inputs:
  aws-key:
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        echo ${REPO}
        echo ${{aws-key}}
        echo ${{ github.event.head_commit.message }}
      shell: bash
