name: 'MADLOG deploy action'
description: 'Description of your action'
inputs:
  aws-key:
    required: true
  aws-secret:
    required: true
  repo:
    required: false
    default: "${{ github.repository }}"
runs:
  using: 'composite'
  steps:
    - run: |
        tar -czf dist.tar.gz --exclude='dist.tar.gz' --exclude="node_modules" --exclude='**/node_modules' * .??*
        #aws s3 cp --quiet dist.tar.gz s3://releases/${{inputs.repo}}/${file}
        echo $AWS_ENDPOINT_URL
        aws s3 cp dist.tar.gz s3://releases/${{inputs.repo}}/${file} --endpoint-url="https://files.madlog.dk"
        curl -v -X POST "https://deploy.madlog.dk/api/uploaded" \
          -d "runid=${{github.run_id}}" \
          -d "repo=${{inputs.repo}}" \
          -d "commit=${{ github.event.head_commit.message }}" \
          -d "branch=${{ github.ref_name }}" \
          -d "author=${{ github.actor }}"
        date
      shell: bash
      env:
        file: "${{github.run_id}}.tar.gz"
        AWS_ACCESS_KEY_ID: "${{ inputs.aws-key }}"
        AWS_SECRET_ACCESS_KEY: "${{ inputs.aws-secret }}"
        AWS_DEFAULT_REGION: "garage"
        AWS_ENDPOINT_URL: "https://files.madlog.dk"
