name: 'MADLOG deploy action'
description: 'Description of your action'
inputs:
  aws-key:
    required: true
  repo:
    required: true
    default: "${{ github.repository }}"
runs:
  using: 'composite'
  steps:
    - run: |
        echo ${REPO}
        echo ${{inputs.aws-key}}
        echo ${{inputs.repo}}
        echo ${{ github.event.head_commit.message }}
      shell: bash
