name: 'MADLOG deploy action'
description: 'Description of your action'
inputs:
  example-input:
    description: 'Input description'
    required: true
    default: 'default value'
outputs:
  example-output:
    description: 'Output description'
runs:
  using: 'composite'
  steps:
    - run: |
        echo ${REPO}
        echo ${{ secrets.FILE_KEY }}
        env

      shell: bash
